### PR TITLE
feat: CreateStubs Pre/Post Processing Script

### PR DESCRIPTION
**Pull request by BradenM**
Adds `process.py`, a small script to handle pre/post processing for `createstubs.py`

Current Usage:

`./process.py minify`

* Removes Logging Dep
* Removes Debug Log calls
* Changes warning/info/error debug calls to print calls
* Executes `pyminifier` to minify
* Outputs file to `-d/--dest` option (defaults to `minified.py`)

`./process.py minify -p esp8266-no-spiram -p <PATCHNAME>...` 

* Same as above
* Loads patch files from ./patches directory
* Applies each `-p <NAME>` patchfile before minification.

Its setup to where any other commands can be added easily if needed.

Also keeps any Cli interface code seperate from main code, so it can just as easily be used like so:
```python
import process

patches = ["foobar/bar.patch", "bar/foo.patch"]
# Returns createstubs.py  as patched/minified string
min_source = process.minify_script(patches=patches)
```

### CODE REVIEW

**Comment by Josverl** [comment]
I tried minify for ESP8622 but found no reduction in memory usage, only in filesize.

I tried switching logging for print, only to find that that used more memory😭
Removing the logging altogether would save memory.


So I was wondering why you added both steps


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by BradenM** [comment]
Interesting, I was under the impression that print would have used less memory. 

The reason I didn't get rid of print all together is cause Pyboard by default times out if it doesn't receive any output after 10 seconds (and therefore rshell/ampy and other tools follow suit). 

When I get some time to work on it later today, I will try removing logging completely and just adding the minimum print calls to prevent a timeout.

**Comment by BradenM** [comment]
Actually, I wonder if it's possible to write directly to `sys.stdout` on Micropython as it is on CPython? Maybe that used less memory? 

I will expirement with this today also.

**Comment by BradenM** [comment]
Okay, here's what I got. Running `./process.py minify` now:
* Removes logging
* Removes all print calls
* Changes [the main report line](https://github.com/Josverl/micropython-stubber/blob/f7ee69552f410344d0311c13a137bcfdd5077f68/createstubs.py#L113) to a `print` call. (Can be disabled by passing `--no-report` flag)
* everything else from earlier

With these changes I got the following results:

**On ESP32 v1.11**:
Normal Lowest: `mem: 93984`
Normal Final: `mem: 93984`

Minified Lowest: `mem: 99280`
Minified Final: `mem: 99280`

**On ESP8266 v1.9.3**:
Normal: n/a
Patched: `MemoryError: memory allocation failed, allocating 652 bytes`

Minified (with patch) Lowest: `mem: 9200`
Minified (with patch) Final: `mem:11136`

Also added:

`./process.py patch <patches>`

* Only applies provided patches

`./process.py minify <-d/--diff> <-n/--no-report>`

* `--diff` will print a diff for each line edited
* `--no-report` will disable single `print` call left in, leaving no output

**Comment by Josverl** [comment]
Hi Braden,

can I ask why you changed the excluded / problematic modules in the patch rather than in the source ?
if that is a reference to changes I made in the esp8266 branch ( commit 
c8b7ec9b3ac499bcd6649134c9ed4533238ef2a0 ) then I think they would be better added to createstubs.py than only to a patch.

I never got around to merging these changes into main, as i did not want to loose the logging capabilities.
using the patch for that is good , but it also makes me wonder how to maintain that patch file as more changes are made to to the main file.

**Comment by BradenM** [comment]
The reason I kept the excluded/problematic modules in the patch was to try and keep the base `./process minify` to make small changes compatible with all devices, whereas the patches were focused on the larger compatibility changes. And yes, all those changes came from that commit :)

I do agree there is an issue with the maintainability of the patch files. 

What do you think of the idea I just pushed to use `patch/*` branches and githooks to generate them? Basically after running `./.githooks/install`, the pre-commit hook with execute:

`git format-patch --stdout --root <patch/branch> -1 > "patches/<branch_name>` 

for every branch that starts with `patch/`.  (See example branch on [my fork](https://github.com/BradenM/micropython-stubber/tree/patch/esp8266-no-spiram))

**Comment by BradenM** [comment]
Also feel I should mention that the reason I made this script was in order to accomplish something like this:

```python

from micropy.lib.stubber import process as stubber
...
        self.log.success("Connected!")
        script = stubber.minify_script(patches=[x, y, or z])
        self.log.info("Executing stubber on pyboard...")
        try:
            pyb.run(script)
        except:
            .....


...
```

in micropy-cli. Figured handling compatibility would be better suited here than in micropy-cli.

**Pull request closed without merging**
